#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLivri.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BiblioLivri")]
	public partial class DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBAutor(TBAutor instance);
    partial void UpdateTBAutor(TBAutor instance);
    partial void DeleteTBAutor(TBAutor instance);
    partial void InsertTBCliente(TBCliente instance);
    partial void UpdateTBCliente(TBCliente instance);
    partial void DeleteTBCliente(TBCliente instance);
    partial void InsertTBCopiaLivro(TBCopiaLivro instance);
    partial void UpdateTBCopiaLivro(TBCopiaLivro instance);
    partial void DeleteTBCopiaLivro(TBCopiaLivro instance);
    partial void InsertTBDoacao(TBDoacao instance);
    partial void UpdateTBDoacao(TBDoacao instance);
    partial void DeleteTBDoacao(TBDoacao instance);
    partial void InsertTBEditora(TBEditora instance);
    partial void UpdateTBEditora(TBEditora instance);
    partial void DeleteTBEditora(TBEditora instance);
    partial void InsertTBEmprestimo(TBEmprestimo instance);
    partial void UpdateTBEmprestimo(TBEmprestimo instance);
    partial void DeleteTBEmprestimo(TBEmprestimo instance);
    partial void InsertTBGenero(TBGenero instance);
    partial void UpdateTBGenero(TBGenero instance);
    partial void DeleteTBGenero(TBGenero instance);
    partial void InsertTBItemDoacao(TBItemDoacao instance);
    partial void UpdateTBItemDoacao(TBItemDoacao instance);
    partial void DeleteTBItemDoacao(TBItemDoacao instance);
    partial void InsertTBItemEmprestimo(TBItemEmprestimo instance);
    partial void UpdateTBItemEmprestimo(TBItemEmprestimo instance);
    partial void DeleteTBItemEmprestimo(TBItemEmprestimo instance);
    partial void InsertTBLivro(TBLivro instance);
    partial void UpdateTBLivro(TBLivro instance);
    partial void DeleteTBLivro(TBLivro instance);
    #endregion
		
		public DataContext() : 
				base(global::BiblioLivri.Model.Properties.Settings.Default.BiblioLivriConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBAutor> TBAutors
		{
			get
			{
				return this.GetTable<TBAutor>();
			}
		}
		
		public System.Data.Linq.Table<TBCliente> TBClientes
		{
			get
			{
				return this.GetTable<TBCliente>();
			}
		}
		
		public System.Data.Linq.Table<TBCopiaLivro> TBCopiaLivros
		{
			get
			{
				return this.GetTable<TBCopiaLivro>();
			}
		}
		
		public System.Data.Linq.Table<TBDoacao> TBDoacaos
		{
			get
			{
				return this.GetTable<TBDoacao>();
			}
		}
		
		public System.Data.Linq.Table<TBEditora> TBEditoras
		{
			get
			{
				return this.GetTable<TBEditora>();
			}
		}
		
		public System.Data.Linq.Table<TBEmprestimo> TBEmprestimos
		{
			get
			{
				return this.GetTable<TBEmprestimo>();
			}
		}
		
		public System.Data.Linq.Table<TBGenero> TBGeneros
		{
			get
			{
				return this.GetTable<TBGenero>();
			}
		}
		
		public System.Data.Linq.Table<TBItemDoacao> TBItemDoacaos
		{
			get
			{
				return this.GetTable<TBItemDoacao>();
			}
		}
		
		public System.Data.Linq.Table<TBItemEmprestimo> TBItemEmprestimos
		{
			get
			{
				return this.GetTable<TBItemEmprestimo>();
			}
		}
		
		public System.Data.Linq.Table<TBLivro> TBLivros
		{
			get
			{
				return this.GetTable<TBLivro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBAutor")]
	public partial class TBAutor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_autor;
		
		private string _AuNome;
		
		private string _AuSobrenome;
		
		private string _AuNacionalidade;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_autorChanging(int value);
    partial void Onid_autorChanged();
    partial void OnAuNomeChanging(string value);
    partial void OnAuNomeChanged();
    partial void OnAuSobrenomeChanging(string value);
    partial void OnAuSobrenomeChanged();
    partial void OnAuNacionalidadeChanging(string value);
    partial void OnAuNacionalidadeChanged();
    #endregion
		
		public TBAutor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_autor", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int id_autor
		{
			get
			{
				return this._id_autor;
			}
			set
			{
				if ((this._id_autor != value))
				{
					this.Onid_autorChanging(value);
					this.SendPropertyChanging();
					this._id_autor = value;
					this.SendPropertyChanged("id_autor");
					this.Onid_autorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuNome", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string AuNome
		{
			get
			{
				return this._AuNome;
			}
			set
			{
				if ((this._AuNome != value))
				{
					this.OnAuNomeChanging(value);
					this.SendPropertyChanging();
					this._AuNome = value;
					this.SendPropertyChanged("AuNome");
					this.OnAuNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuSobrenome", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string AuSobrenome
		{
			get
			{
				return this._AuSobrenome;
			}
			set
			{
				if ((this._AuSobrenome != value))
				{
					this.OnAuSobrenomeChanging(value);
					this.SendPropertyChanging();
					this._AuSobrenome = value;
					this.SendPropertyChanged("AuSobrenome");
					this.OnAuSobrenomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuNacionalidade", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string AuNacionalidade
		{
			get
			{
				return this._AuNacionalidade;
			}
			set
			{
				if ((this._AuNacionalidade != value))
				{
					this.OnAuNacionalidadeChanging(value);
					this.SendPropertyChanging();
					this._AuNacionalidade = value;
					this.SendPropertyChanged("AuNacionalidade");
					this.OnAuNacionalidadeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBCliente")]
	public partial class TBCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CliNumCartao;
		
		private string _CliSobrenome;
		
		private string _CliNome;
		
		private string _CliEndereco;
		
		private string _CliCidade;
		
		private string _CliCEP;
		
		private string _CliTelefone;
		
		private string _CliEmail;
		
		private string _CliCelular;
		
		private string _CliCPF;
		
		private string _CliEstado;
		
		private string _CliPais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCliNumCartaoChanging(int value);
    partial void OnCliNumCartaoChanged();
    partial void OnCliSobrenomeChanging(string value);
    partial void OnCliSobrenomeChanged();
    partial void OnCliNomeChanging(string value);
    partial void OnCliNomeChanged();
    partial void OnCliEnderecoChanging(string value);
    partial void OnCliEnderecoChanged();
    partial void OnCliCidadeChanging(string value);
    partial void OnCliCidadeChanged();
    partial void OnCliCEPChanging(string value);
    partial void OnCliCEPChanged();
    partial void OnCliTelefoneChanging(string value);
    partial void OnCliTelefoneChanged();
    partial void OnCliEmailChanging(string value);
    partial void OnCliEmailChanged();
    partial void OnCliCelularChanging(string value);
    partial void OnCliCelularChanged();
    partial void OnCliCPFChanging(string value);
    partial void OnCliCPFChanged();
    partial void OnCliEstadoChanging(string value);
    partial void OnCliEstadoChanged();
    partial void OnCliPaisChanging(string value);
    partial void OnCliPaisChanged();
    #endregion
		
		public TBCliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliNumCartao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int CliNumCartao
		{
			get
			{
				return this._CliNumCartao;
			}
			set
			{
				if ((this._CliNumCartao != value))
				{
					this.OnCliNumCartaoChanging(value);
					this.SendPropertyChanging();
					this._CliNumCartao = value;
					this.SendPropertyChanged("CliNumCartao");
					this.OnCliNumCartaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliSobrenome", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CliSobrenome
		{
			get
			{
				return this._CliSobrenome;
			}
			set
			{
				if ((this._CliSobrenome != value))
				{
					this.OnCliSobrenomeChanging(value);
					this.SendPropertyChanging();
					this._CliSobrenome = value;
					this.SendPropertyChanged("CliSobrenome");
					this.OnCliSobrenomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliNome", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CliNome
		{
			get
			{
				return this._CliNome;
			}
			set
			{
				if ((this._CliNome != value))
				{
					this.OnCliNomeChanging(value);
					this.SendPropertyChanging();
					this._CliNome = value;
					this.SendPropertyChanged("CliNome");
					this.OnCliNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliEndereco", DbType="VarChar(150) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CliEndereco
		{
			get
			{
				return this._CliEndereco;
			}
			set
			{
				if ((this._CliEndereco != value))
				{
					this.OnCliEnderecoChanging(value);
					this.SendPropertyChanging();
					this._CliEndereco = value;
					this.SendPropertyChanged("CliEndereco");
					this.OnCliEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliCidade", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CliCidade
		{
			get
			{
				return this._CliCidade;
			}
			set
			{
				if ((this._CliCidade != value))
				{
					this.OnCliCidadeChanging(value);
					this.SendPropertyChanging();
					this._CliCidade = value;
					this.SendPropertyChanged("CliCidade");
					this.OnCliCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliCEP", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CliCEP
		{
			get
			{
				return this._CliCEP;
			}
			set
			{
				if ((this._CliCEP != value))
				{
					this.OnCliCEPChanging(value);
					this.SendPropertyChanging();
					this._CliCEP = value;
					this.SendPropertyChanged("CliCEP");
					this.OnCliCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliTelefone", DbType="VarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string CliTelefone
		{
			get
			{
				return this._CliTelefone;
			}
			set
			{
				if ((this._CliTelefone != value))
				{
					this.OnCliTelefoneChanging(value);
					this.SendPropertyChanging();
					this._CliTelefone = value;
					this.SendPropertyChanged("CliTelefone");
					this.OnCliTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliEmail", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CliEmail
		{
			get
			{
				return this._CliEmail;
			}
			set
			{
				if ((this._CliEmail != value))
				{
					this.OnCliEmailChanging(value);
					this.SendPropertyChanging();
					this._CliEmail = value;
					this.SendPropertyChanged("CliEmail");
					this.OnCliEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliCelular", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CliCelular
		{
			get
			{
				return this._CliCelular;
			}
			set
			{
				if ((this._CliCelular != value))
				{
					this.OnCliCelularChanging(value);
					this.SendPropertyChanging();
					this._CliCelular = value;
					this.SendPropertyChanged("CliCelular");
					this.OnCliCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliCPF", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CliCPF
		{
			get
			{
				return this._CliCPF;
			}
			set
			{
				if ((this._CliCPF != value))
				{
					this.OnCliCPFChanging(value);
					this.SendPropertyChanging();
					this._CliCPF = value;
					this.SendPropertyChanged("CliCPF");
					this.OnCliCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliEstado", DbType="VarChar(2) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CliEstado
		{
			get
			{
				return this._CliEstado;
			}
			set
			{
				if ((this._CliEstado != value))
				{
					this.OnCliEstadoChanging(value);
					this.SendPropertyChanging();
					this._CliEstado = value;
					this.SendPropertyChanged("CliEstado");
					this.OnCliEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliPais", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CliPais
		{
			get
			{
				return this._CliPais;
			}
			set
			{
				if ((this._CliPais != value))
				{
					this.OnCliPaisChanging(value);
					this.SendPropertyChanging();
					this._CliPais = value;
					this.SendPropertyChanged("CliPais");
					this.OnCliPaisChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBCopiaLivro")]
	public partial class TBCopiaLivro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CoISBN;
		
		private int _CoNumCopia;
		
		private System.DateTime _DataAquisicao;
		
		private string _CoEdicao;
		
		private string _CoIdioma;
		
		private string _CoAno;
		
		private bool _CoEmprestado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCoISBNChanging(string value);
    partial void OnCoISBNChanged();
    partial void OnCoNumCopiaChanging(int value);
    partial void OnCoNumCopiaChanged();
    partial void OnDataAquisicaoChanging(System.DateTime value);
    partial void OnDataAquisicaoChanged();
    partial void OnCoEdicaoChanging(string value);
    partial void OnCoEdicaoChanged();
    partial void OnCoIdiomaChanging(string value);
    partial void OnCoIdiomaChanged();
    partial void OnCoAnoChanging(string value);
    partial void OnCoAnoChanged();
    partial void OnCoEmprestadoChanging(bool value);
    partial void OnCoEmprestadoChanged();
    #endregion
		
		public TBCopiaLivro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoISBN", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CoISBN
		{
			get
			{
				return this._CoISBN;
			}
			set
			{
				if ((this._CoISBN != value))
				{
					this.OnCoISBNChanging(value);
					this.SendPropertyChanging();
					this._CoISBN = value;
					this.SendPropertyChanged("CoISBN");
					this.OnCoISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoNumCopia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int CoNumCopia
		{
			get
			{
				return this._CoNumCopia;
			}
			set
			{
				if ((this._CoNumCopia != value))
				{
					this.OnCoNumCopiaChanging(value);
					this.SendPropertyChanging();
					this._CoNumCopia = value;
					this.SendPropertyChanged("CoNumCopia");
					this.OnCoNumCopiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAquisicao", DbType="Date NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime DataAquisicao
		{
			get
			{
				return this._DataAquisicao;
			}
			set
			{
				if ((this._DataAquisicao != value))
				{
					this.OnDataAquisicaoChanging(value);
					this.SendPropertyChanging();
					this._DataAquisicao = value;
					this.SendPropertyChanged("DataAquisicao");
					this.OnDataAquisicaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoEdicao", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CoEdicao
		{
			get
			{
				return this._CoEdicao;
			}
			set
			{
				if ((this._CoEdicao != value))
				{
					this.OnCoEdicaoChanging(value);
					this.SendPropertyChanging();
					this._CoEdicao = value;
					this.SendPropertyChanged("CoEdicao");
					this.OnCoEdicaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoIdioma", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CoIdioma
		{
			get
			{
				return this._CoIdioma;
			}
			set
			{
				if ((this._CoIdioma != value))
				{
					this.OnCoIdiomaChanging(value);
					this.SendPropertyChanging();
					this._CoIdioma = value;
					this.SendPropertyChanged("CoIdioma");
					this.OnCoIdiomaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoAno", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CoAno
		{
			get
			{
				return this._CoAno;
			}
			set
			{
				if ((this._CoAno != value))
				{
					this.OnCoAnoChanging(value);
					this.SendPropertyChanging();
					this._CoAno = value;
					this.SendPropertyChanged("CoAno");
					this.OnCoAnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoEmprestado", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool CoEmprestado
		{
			get
			{
				return this._CoEmprestado;
			}
			set
			{
				if ((this._CoEmprestado != value))
				{
					this.OnCoEmprestadoChanging(value);
					this.SendPropertyChanging();
					this._CoEmprestado = value;
					this.SendPropertyChanged("CoEmprestado");
					this.OnCoEmprestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBDoacao")]
	public partial class TBDoacao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DoNumDoacao;
		
		private int _DoNumClienteDoador;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDoNumDoacaoChanging(int value);
    partial void OnDoNumDoacaoChanged();
    partial void OnDoNumClienteDoadorChanging(int value);
    partial void OnDoNumClienteDoadorChanged();
    #endregion
		
		public TBDoacao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoNumDoacao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int DoNumDoacao
		{
			get
			{
				return this._DoNumDoacao;
			}
			set
			{
				if ((this._DoNumDoacao != value))
				{
					this.OnDoNumDoacaoChanging(value);
					this.SendPropertyChanging();
					this._DoNumDoacao = value;
					this.SendPropertyChanged("DoNumDoacao");
					this.OnDoNumDoacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoNumClienteDoador", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int DoNumClienteDoador
		{
			get
			{
				return this._DoNumClienteDoador;
			}
			set
			{
				if ((this._DoNumClienteDoador != value))
				{
					this.OnDoNumClienteDoadorChanging(value);
					this.SendPropertyChanging();
					this._DoNumClienteDoador = value;
					this.SendPropertyChanged("DoNumClienteDoador");
					this.OnDoNumClienteDoadorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBEditora")]
	public partial class TBEditora : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_editora;
		
		private string _EdNome;
		
		private string _EdCidade;
		
		private string _EdEmail;
		
		private string _EdTelefone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_editoraChanging(int value);
    partial void Onid_editoraChanged();
    partial void OnEdNomeChanging(string value);
    partial void OnEdNomeChanged();
    partial void OnEdCidadeChanging(string value);
    partial void OnEdCidadeChanged();
    partial void OnEdEmailChanging(string value);
    partial void OnEdEmailChanged();
    partial void OnEdTelefoneChanging(string value);
    partial void OnEdTelefoneChanged();
    #endregion
		
		public TBEditora()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_editora", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int id_editora
		{
			get
			{
				return this._id_editora;
			}
			set
			{
				if ((this._id_editora != value))
				{
					this.Onid_editoraChanging(value);
					this.SendPropertyChanging();
					this._id_editora = value;
					this.SendPropertyChanged("id_editora");
					this.Onid_editoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EdNome", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string EdNome
		{
			get
			{
				return this._EdNome;
			}
			set
			{
				if ((this._EdNome != value))
				{
					this.OnEdNomeChanging(value);
					this.SendPropertyChanging();
					this._EdNome = value;
					this.SendPropertyChanged("EdNome");
					this.OnEdNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EdCidade", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string EdCidade
		{
			get
			{
				return this._EdCidade;
			}
			set
			{
				if ((this._EdCidade != value))
				{
					this.OnEdCidadeChanging(value);
					this.SendPropertyChanging();
					this._EdCidade = value;
					this.SendPropertyChanged("EdCidade");
					this.OnEdCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EdEmail", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string EdEmail
		{
			get
			{
				return this._EdEmail;
			}
			set
			{
				if ((this._EdEmail != value))
				{
					this.OnEdEmailChanging(value);
					this.SendPropertyChanging();
					this._EdEmail = value;
					this.SendPropertyChanged("EdEmail");
					this.OnEdEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EdTelefone", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string EdTelefone
		{
			get
			{
				return this._EdTelefone;
			}
			set
			{
				if ((this._EdTelefone != value))
				{
					this.OnEdTelefoneChanging(value);
					this.SendPropertyChanging();
					this._EdTelefone = value;
					this.SendPropertyChanged("EdTelefone");
					this.OnEdTelefoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBEmprestimo")]
	public partial class TBEmprestimo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmpNumEmprestimo;
		
		private int _EmpNumCartao;
		
		private System.DateTime _EmpDataDevolucao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmpNumEmprestimoChanging(int value);
    partial void OnEmpNumEmprestimoChanged();
    partial void OnEmpNumCartaoChanging(int value);
    partial void OnEmpNumCartaoChanged();
    partial void OnEmpDataDevolucaoChanging(System.DateTime value);
    partial void OnEmpDataDevolucaoChanged();
    #endregion
		
		public TBEmprestimo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNumEmprestimo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int EmpNumEmprestimo
		{
			get
			{
				return this._EmpNumEmprestimo;
			}
			set
			{
				if ((this._EmpNumEmprestimo != value))
				{
					this.OnEmpNumEmprestimoChanging(value);
					this.SendPropertyChanging();
					this._EmpNumEmprestimo = value;
					this.SendPropertyChanged("EmpNumEmprestimo");
					this.OnEmpNumEmprestimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNumCartao", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int EmpNumCartao
		{
			get
			{
				return this._EmpNumCartao;
			}
			set
			{
				if ((this._EmpNumCartao != value))
				{
					this.OnEmpNumCartaoChanging(value);
					this.SendPropertyChanging();
					this._EmpNumCartao = value;
					this.SendPropertyChanged("EmpNumCartao");
					this.OnEmpNumCartaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpDataDevolucao", DbType="Date NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime EmpDataDevolucao
		{
			get
			{
				return this._EmpDataDevolucao;
			}
			set
			{
				if ((this._EmpDataDevolucao != value))
				{
					this.OnEmpDataDevolucaoChanging(value);
					this.SendPropertyChanging();
					this._EmpDataDevolucao = value;
					this.SendPropertyChanged("EmpDataDevolucao");
					this.OnEmpDataDevolucaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBGenero")]
	public partial class TBGenero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_genero;
		
		private string _GeDescricao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_generoChanging(int value);
    partial void Onid_generoChanged();
    partial void OnGeDescricaoChanging(string value);
    partial void OnGeDescricaoChanged();
    #endregion
		
		public TBGenero()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_genero", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int id_genero
		{
			get
			{
				return this._id_genero;
			}
			set
			{
				if ((this._id_genero != value))
				{
					this.Onid_generoChanging(value);
					this.SendPropertyChanging();
					this._id_genero = value;
					this.SendPropertyChanged("id_genero");
					this.Onid_generoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeDescricao", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string GeDescricao
		{
			get
			{
				return this._GeDescricao;
			}
			set
			{
				if ((this._GeDescricao != value))
				{
					this.OnGeDescricaoChanging(value);
					this.SendPropertyChanging();
					this._GeDescricao = value;
					this.SendPropertyChanged("GeDescricao");
					this.OnGeDescricaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBItemDoacao")]
	public partial class TBItemDoacao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ItemNumDoacao;
		
		private int _ItemNumCopia;
		
		private System.DateTime _ItemDataDoacao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemNumDoacaoChanging(int value);
    partial void OnItemNumDoacaoChanged();
    partial void OnItemNumCopiaChanging(int value);
    partial void OnItemNumCopiaChanged();
    partial void OnItemDataDoacaoChanging(System.DateTime value);
    partial void OnItemDataDoacaoChanged();
    #endregion
		
		public TBItemDoacao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNumDoacao", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int ItemNumDoacao
		{
			get
			{
				return this._ItemNumDoacao;
			}
			set
			{
				if ((this._ItemNumDoacao != value))
				{
					this.OnItemNumDoacaoChanging(value);
					this.SendPropertyChanging();
					this._ItemNumDoacao = value;
					this.SendPropertyChanged("ItemNumDoacao");
					this.OnItemNumDoacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNumCopia", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int ItemNumCopia
		{
			get
			{
				return this._ItemNumCopia;
			}
			set
			{
				if ((this._ItemNumCopia != value))
				{
					this.OnItemNumCopiaChanging(value);
					this.SendPropertyChanging();
					this._ItemNumCopia = value;
					this.SendPropertyChanged("ItemNumCopia");
					this.OnItemNumCopiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemDataDoacao", DbType="Date NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime ItemDataDoacao
		{
			get
			{
				return this._ItemDataDoacao;
			}
			set
			{
				if ((this._ItemDataDoacao != value))
				{
					this.OnItemDataDoacaoChanging(value);
					this.SendPropertyChanging();
					this._ItemDataDoacao = value;
					this.SendPropertyChanged("ItemDataDoacao");
					this.OnItemDataDoacaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBItemEmprestimo")]
	public partial class TBItemEmprestimo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ItemNumEmprestimo;
		
		private int _ItemNumCopia;
		
		private System.DateTime _ItemDataEmprestimo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnItemNumEmprestimoChanging(int value);
    partial void OnItemNumEmprestimoChanged();
    partial void OnItemNumCopiaChanging(int value);
    partial void OnItemNumCopiaChanged();
    partial void OnItemDataEmprestimoChanging(System.DateTime value);
    partial void OnItemDataEmprestimoChanged();
    #endregion
		
		public TBItemEmprestimo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNumEmprestimo", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int ItemNumEmprestimo
		{
			get
			{
				return this._ItemNumEmprestimo;
			}
			set
			{
				if ((this._ItemNumEmprestimo != value))
				{
					this.OnItemNumEmprestimoChanging(value);
					this.SendPropertyChanging();
					this._ItemNumEmprestimo = value;
					this.SendPropertyChanged("ItemNumEmprestimo");
					this.OnItemNumEmprestimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNumCopia", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int ItemNumCopia
		{
			get
			{
				return this._ItemNumCopia;
			}
			set
			{
				if ((this._ItemNumCopia != value))
				{
					this.OnItemNumCopiaChanging(value);
					this.SendPropertyChanging();
					this._ItemNumCopia = value;
					this.SendPropertyChanged("ItemNumCopia");
					this.OnItemNumCopiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemDataEmprestimo", DbType="Date NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime ItemDataEmprestimo
		{
			get
			{
				return this._ItemDataEmprestimo;
			}
			set
			{
				if ((this._ItemDataEmprestimo != value))
				{
					this.OnItemDataEmprestimoChanging(value);
					this.SendPropertyChanging();
					this._ItemDataEmprestimo = value;
					this.SendPropertyChanged("ItemDataEmprestimo");
					this.OnItemDataEmprestimoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLivro")]
	public partial class TBLivro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LiISBN;
		
		private int _ID_Editora;
		
		private string _LiTitulo;
		
		private string _LiCDU;
		
		private string _LiPagina;
		
		private int _id_genero;
		
		private int _id_autor;
		
		private byte[] _LiCapa;
		
		private string _LiPais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLiISBNChanging(string value);
    partial void OnLiISBNChanged();
    partial void OnID_EditoraChanging(int value);
    partial void OnID_EditoraChanged();
    partial void OnLiTituloChanging(string value);
    partial void OnLiTituloChanged();
    partial void OnLiCDUChanging(string value);
    partial void OnLiCDUChanged();
    partial void OnLiPaginaChanging(string value);
    partial void OnLiPaginaChanged();
    partial void Onid_generoChanging(int value);
    partial void Onid_generoChanged();
    partial void Onid_autorChanging(int value);
    partial void Onid_autorChanged();
    partial void OnLiCapaChanging(byte[] value);
    partial void OnLiCapaChanged();
    partial void OnLiPaisChanging(string value);
    partial void OnLiPaisChanged();
    #endregion
		
		public TBLivro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LiISBN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string LiISBN
		{
			get
			{
				return this._LiISBN;
			}
			set
			{
				if ((this._LiISBN != value))
				{
					this.OnLiISBNChanging(value);
					this.SendPropertyChanging();
					this._LiISBN = value;
					this.SendPropertyChanged("LiISBN");
					this.OnLiISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Editora", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int ID_Editora
		{
			get
			{
				return this._ID_Editora;
			}
			set
			{
				if ((this._ID_Editora != value))
				{
					this.OnID_EditoraChanging(value);
					this.SendPropertyChanging();
					this._ID_Editora = value;
					this.SendPropertyChanged("ID_Editora");
					this.OnID_EditoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LiTitulo", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string LiTitulo
		{
			get
			{
				return this._LiTitulo;
			}
			set
			{
				if ((this._LiTitulo != value))
				{
					this.OnLiTituloChanging(value);
					this.SendPropertyChanging();
					this._LiTitulo = value;
					this.SendPropertyChanged("LiTitulo");
					this.OnLiTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LiCDU", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string LiCDU
		{
			get
			{
				return this._LiCDU;
			}
			set
			{
				if ((this._LiCDU != value))
				{
					this.OnLiCDUChanging(value);
					this.SendPropertyChanging();
					this._LiCDU = value;
					this.SendPropertyChanged("LiCDU");
					this.OnLiCDUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LiPagina", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string LiPagina
		{
			get
			{
				return this._LiPagina;
			}
			set
			{
				if ((this._LiPagina != value))
				{
					this.OnLiPaginaChanging(value);
					this.SendPropertyChanging();
					this._LiPagina = value;
					this.SendPropertyChanged("LiPagina");
					this.OnLiPaginaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_genero", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int id_genero
		{
			get
			{
				return this._id_genero;
			}
			set
			{
				if ((this._id_genero != value))
				{
					this.Onid_generoChanging(value);
					this.SendPropertyChanging();
					this._id_genero = value;
					this.SendPropertyChanged("id_genero");
					this.Onid_generoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_autor", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int id_autor
		{
			get
			{
				return this._id_autor;
			}
			set
			{
				if ((this._id_autor != value))
				{
					this.Onid_autorChanging(value);
					this.SendPropertyChanging();
					this._id_autor = value;
					this.SendPropertyChanged("id_autor");
					this.Onid_autorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LiCapa", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public byte[] LiCapa
		{
			get
			{
				return this._LiCapa;
			}
			set
			{
				if ((this._LiCapa != value))
				{
					this.OnLiCapaChanging(value);
					this.SendPropertyChanging();
					this._LiCapa = value;
					this.SendPropertyChanged("LiCapa");
					this.OnLiCapaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LiPais", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string LiPais
		{
			get
			{
				return this._LiPais;
			}
			set
			{
				if ((this._LiPais != value))
				{
					this.OnLiPaisChanging(value);
					this.SendPropertyChanging();
					this._LiPais = value;
					this.SendPropertyChanged("LiPais");
					this.OnLiPaisChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
