//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLivri.View.CPeriodico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBPeriodico", Namespace="http://schemas.datacontract.org/2004/07/BiblioLivri.Model")]
    [System.SerializableAttribute()]
    public partial class TBPeriodico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReAnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReISSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReIdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReMesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReNumPaginasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RePaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReTituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_EditoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_revistaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReAno {
            get {
                return this.ReAnoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReAnoField, value) != true)) {
                    this.ReAnoField = value;
                    this.RaisePropertyChanged("ReAno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReISSN {
            get {
                return this.ReISSNField;
            }
            set {
                if ((object.ReferenceEquals(this.ReISSNField, value) != true)) {
                    this.ReISSNField = value;
                    this.RaisePropertyChanged("ReISSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReIdioma {
            get {
                return this.ReIdiomaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReIdiomaField, value) != true)) {
                    this.ReIdiomaField = value;
                    this.RaisePropertyChanged("ReIdioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReMes {
            get {
                return this.ReMesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReMesField, value) != true)) {
                    this.ReMesField = value;
                    this.RaisePropertyChanged("ReMes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReNumPaginas {
            get {
                return this.ReNumPaginasField;
            }
            set {
                if ((object.ReferenceEquals(this.ReNumPaginasField, value) != true)) {
                    this.ReNumPaginasField = value;
                    this.RaisePropertyChanged("ReNumPaginas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RePais {
            get {
                return this.RePaisField;
            }
            set {
                if ((object.ReferenceEquals(this.RePaisField, value) != true)) {
                    this.RePaisField = value;
                    this.RaisePropertyChanged("RePais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReTipo {
            get {
                return this.ReTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReTipoField, value) != true)) {
                    this.ReTipoField = value;
                    this.RaisePropertyChanged("ReTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReTitulo {
            get {
                return this.ReTituloField;
            }
            set {
                if ((object.ReferenceEquals(this.ReTituloField, value) != true)) {
                    this.ReTituloField = value;
                    this.RaisePropertyChanged("ReTitulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Editora {
            get {
                return this.id_EditoraField;
            }
            set {
                if ((this.id_EditoraField.Equals(value) != true)) {
                    this.id_EditoraField = value;
                    this.RaisePropertyChanged("id_Editora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_revista {
            get {
                return this.id_revistaField;
            }
            set {
                if ((this.id_revistaField.Equals(value) != true)) {
                    this.id_revistaField = value;
                    this.RaisePropertyChanged("id_revista");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CPeriodico.ICPeriodico")]
    public interface ICPeriodico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/Incluir", ReplyAction="http://tempuri.org/ICPeriodico/IncluirResponse")]
        void Incluir(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/Incluir", ReplyAction="http://tempuri.org/ICPeriodico/IncluirResponse")]
        System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/Alterar", ReplyAction="http://tempuri.org/ICPeriodico/AlterarResponse")]
        void Alterar(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/Alterar", ReplyAction="http://tempuri.org/ICPeriodico/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/Excluir", ReplyAction="http://tempuri.org/ICPeriodico/ExcluirResponse")]
        void Excluir(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/Excluir", ReplyAction="http://tempuri.org/ICPeriodico/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/SelecionaPK", ReplyAction="http://tempuri.org/ICPeriodico/SelecionaPKResponse")]
        BiblioLivri.View.CPeriodico.TBPeriodico SelecionaPK(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/SelecionaPK", ReplyAction="http://tempuri.org/ICPeriodico/SelecionaPKResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CPeriodico.TBPeriodico> SelecionaPKAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/SelecionaTodos", ReplyAction="http://tempuri.org/ICPeriodico/SelecionaTodosResponse")]
        BiblioLivri.View.CPeriodico.TBPeriodico[] SelecionaTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/SelecionaTodos", ReplyAction="http://tempuri.org/ICPeriodico/SelecionaTodosResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CPeriodico.TBPeriodico[]> SelecionaTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/ValidaISSN", ReplyAction="http://tempuri.org/ICPeriodico/ValidaISSNResponse")]
        bool ValidaISSN(string ISSN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPeriodico/ValidaISSN", ReplyAction="http://tempuri.org/ICPeriodico/ValidaISSNResponse")]
        System.Threading.Tasks.Task<bool> ValidaISSNAsync(string ISSN);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPeriodicoChannel : BiblioLivri.View.CPeriodico.ICPeriodico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPeriodicoClient : System.ServiceModel.ClientBase<BiblioLivri.View.CPeriodico.ICPeriodico>, BiblioLivri.View.CPeriodico.ICPeriodico {
        
        public CPeriodicoClient() {
        }
        
        public CPeriodicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPeriodicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPeriodicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPeriodicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Incluir(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico) {
            base.Channel.Incluir(oPeriodico);
        }
        
        public System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico) {
            return base.Channel.IncluirAsync(oPeriodico);
        }
        
        public void Alterar(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico) {
            base.Channel.Alterar(oPeriodico);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico) {
            return base.Channel.AlterarAsync(oPeriodico);
        }
        
        public void Excluir(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico) {
            base.Channel.Excluir(oPeriodico);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CPeriodico.TBPeriodico oPeriodico) {
            return base.Channel.ExcluirAsync(oPeriodico);
        }
        
        public BiblioLivri.View.CPeriodico.TBPeriodico SelecionaPK(int codigo) {
            return base.Channel.SelecionaPK(codigo);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CPeriodico.TBPeriodico> SelecionaPKAsync(int codigo) {
            return base.Channel.SelecionaPKAsync(codigo);
        }
        
        public BiblioLivri.View.CPeriodico.TBPeriodico[] SelecionaTodos() {
            return base.Channel.SelecionaTodos();
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CPeriodico.TBPeriodico[]> SelecionaTodosAsync() {
            return base.Channel.SelecionaTodosAsync();
        }
        
        public bool ValidaISSN(string ISSN) {
            return base.Channel.ValidaISSN(ISSN);
        }
        
        public System.Threading.Tasks.Task<bool> ValidaISSNAsync(string ISSN) {
            return base.Channel.ValidaISSNAsync(ISSN);
        }
    }
}
