//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLivri.View.CEmprestimo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBEmprestimo", Namespace="http://schemas.datacontract.org/2004/07/BiblioLivri.Model")]
    [System.SerializableAttribute()]
    public partial class TBEmprestimo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EmpDataDevolucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpNumCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpNumEmprestimoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EmpDataDevolucao {
            get {
                return this.EmpDataDevolucaoField;
            }
            set {
                if ((this.EmpDataDevolucaoField.Equals(value) != true)) {
                    this.EmpDataDevolucaoField = value;
                    this.RaisePropertyChanged("EmpDataDevolucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpNumCartao {
            get {
                return this.EmpNumCartaoField;
            }
            set {
                if ((this.EmpNumCartaoField.Equals(value) != true)) {
                    this.EmpNumCartaoField = value;
                    this.RaisePropertyChanged("EmpNumCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpNumEmprestimo {
            get {
                return this.EmpNumEmprestimoField;
            }
            set {
                if ((this.EmpNumEmprestimoField.Equals(value) != true)) {
                    this.EmpNumEmprestimoField = value;
                    this.RaisePropertyChanged("EmpNumEmprestimo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CEmprestimo.ICEmprestimo")]
    public interface ICEmprestimo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/Incluir", ReplyAction="http://tempuri.org/ICEmprestimo/IncluirResponse")]
        int[] Incluir(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/Incluir", ReplyAction="http://tempuri.org/ICEmprestimo/IncluirResponse")]
        System.Threading.Tasks.Task<int[]> IncluirAsync(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/Alterar", ReplyAction="http://tempuri.org/ICEmprestimo/AlterarResponse")]
        void Alterar(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/Alterar", ReplyAction="http://tempuri.org/ICEmprestimo/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/Excluir", ReplyAction="http://tempuri.org/ICEmprestimo/ExcluirResponse")]
        void Excluir(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/Excluir", ReplyAction="http://tempuri.org/ICEmprestimo/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/SelecionaPK", ReplyAction="http://tempuri.org/ICEmprestimo/SelecionaPKResponse")]
        BiblioLivri.View.CEmprestimo.TBEmprestimo SelecionaPK(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/SelecionaPK", ReplyAction="http://tempuri.org/ICEmprestimo/SelecionaPKResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CEmprestimo.TBEmprestimo> SelecionaPKAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/SelecionaTodos", ReplyAction="http://tempuri.org/ICEmprestimo/SelecionaTodosResponse")]
        BiblioLivri.View.CEmprestimo.TBEmprestimo[] SelecionaTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/SelecionaTodos", ReplyAction="http://tempuri.org/ICEmprestimo/SelecionaTodosResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CEmprestimo.TBEmprestimo[]> SelecionaTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/SelecionaTodosCriterio", ReplyAction="http://tempuri.org/ICEmprestimo/SelecionaTodosCriterioResponse")]
        BiblioLivri.View.CEmprestimo.TBEmprestimo[] SelecionaTodosCriterio(string Criterio, int TipoPesquisa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICEmprestimo/SelecionaTodosCriterio", ReplyAction="http://tempuri.org/ICEmprestimo/SelecionaTodosCriterioResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CEmprestimo.TBEmprestimo[]> SelecionaTodosCriterioAsync(string Criterio, int TipoPesquisa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICEmprestimoChannel : BiblioLivri.View.CEmprestimo.ICEmprestimo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CEmprestimoClient : System.ServiceModel.ClientBase<BiblioLivri.View.CEmprestimo.ICEmprestimo>, BiblioLivri.View.CEmprestimo.ICEmprestimo {
        
        public CEmprestimoClient() {
        }
        
        public CEmprestimoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CEmprestimoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CEmprestimoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CEmprestimoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] Incluir(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo) {
            return base.Channel.Incluir(oEmprestimo);
        }
        
        public System.Threading.Tasks.Task<int[]> IncluirAsync(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo) {
            return base.Channel.IncluirAsync(oEmprestimo);
        }
        
        public void Alterar(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo) {
            base.Channel.Alterar(oEmprestimo);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo) {
            return base.Channel.AlterarAsync(oEmprestimo);
        }
        
        public void Excluir(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo) {
            base.Channel.Excluir(oEmprestimo);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CEmprestimo.TBEmprestimo oEmprestimo) {
            return base.Channel.ExcluirAsync(oEmprestimo);
        }
        
        public BiblioLivri.View.CEmprestimo.TBEmprestimo SelecionaPK(int codigo) {
            return base.Channel.SelecionaPK(codigo);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CEmprestimo.TBEmprestimo> SelecionaPKAsync(int codigo) {
            return base.Channel.SelecionaPKAsync(codigo);
        }
        
        public BiblioLivri.View.CEmprestimo.TBEmprestimo[] SelecionaTodos() {
            return base.Channel.SelecionaTodos();
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CEmprestimo.TBEmprestimo[]> SelecionaTodosAsync() {
            return base.Channel.SelecionaTodosAsync();
        }
        
        public BiblioLivri.View.CEmprestimo.TBEmprestimo[] SelecionaTodosCriterio(string Criterio, int TipoPesquisa) {
            return base.Channel.SelecionaTodosCriterio(Criterio, TipoPesquisa);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CEmprestimo.TBEmprestimo[]> SelecionaTodosCriterioAsync(string Criterio, int TipoPesquisa) {
            return base.Channel.SelecionaTodosCriterioAsync(Criterio, TipoPesquisa);
        }
    }
}
