//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLivri.View.CDoacao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBDoacao", Namespace="http://schemas.datacontract.org/2004/07/BiblioLivri.Model")]
    [System.SerializableAttribute()]
    public partial class TBDoacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DoNumClienteDoadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DoNumDoacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoNumClienteDoador {
            get {
                return this.DoNumClienteDoadorField;
            }
            set {
                if ((this.DoNumClienteDoadorField.Equals(value) != true)) {
                    this.DoNumClienteDoadorField = value;
                    this.RaisePropertyChanged("DoNumClienteDoador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoNumDoacao {
            get {
                return this.DoNumDoacaoField;
            }
            set {
                if ((this.DoNumDoacaoField.Equals(value) != true)) {
                    this.DoNumDoacaoField = value;
                    this.RaisePropertyChanged("DoNumDoacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CDoacao.ICDoacao")]
    public interface ICDoacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/Incluir", ReplyAction="http://tempuri.org/ICDoacao/IncluirResponse")]
        int[] Incluir(BiblioLivri.View.CDoacao.TBDoacao oDoacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/Incluir", ReplyAction="http://tempuri.org/ICDoacao/IncluirResponse")]
        System.Threading.Tasks.Task<int[]> IncluirAsync(BiblioLivri.View.CDoacao.TBDoacao oDoacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/Alterar", ReplyAction="http://tempuri.org/ICDoacao/AlterarResponse")]
        void Alterar(BiblioLivri.View.CDoacao.TBDoacao oDoacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/Alterar", ReplyAction="http://tempuri.org/ICDoacao/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CDoacao.TBDoacao oDoacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/Excluir", ReplyAction="http://tempuri.org/ICDoacao/ExcluirResponse")]
        void Excluir(BiblioLivri.View.CDoacao.TBDoacao oDoacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/Excluir", ReplyAction="http://tempuri.org/ICDoacao/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CDoacao.TBDoacao oDoacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/SelecionaPK", ReplyAction="http://tempuri.org/ICDoacao/SelecionaPKResponse")]
        BiblioLivri.View.CDoacao.TBDoacao SelecionaPK(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/SelecionaPK", ReplyAction="http://tempuri.org/ICDoacao/SelecionaPKResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CDoacao.TBDoacao> SelecionaPKAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/SelecionaTodos", ReplyAction="http://tempuri.org/ICDoacao/SelecionaTodosResponse")]
        BiblioLivri.View.CDoacao.TBDoacao[] SelecionaTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/SelecionaTodos", ReplyAction="http://tempuri.org/ICDoacao/SelecionaTodosResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CDoacao.TBDoacao[]> SelecionaTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/SelecionaTodosCriterio", ReplyAction="http://tempuri.org/ICDoacao/SelecionaTodosCriterioResponse")]
        BiblioLivri.View.CDoacao.TBDoacao[] SelecionaTodosCriterio(string Criterio, int TipoPesquisa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDoacao/SelecionaTodosCriterio", ReplyAction="http://tempuri.org/ICDoacao/SelecionaTodosCriterioResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CDoacao.TBDoacao[]> SelecionaTodosCriterioAsync(string Criterio, int TipoPesquisa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICDoacaoChannel : BiblioLivri.View.CDoacao.ICDoacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDoacaoClient : System.ServiceModel.ClientBase<BiblioLivri.View.CDoacao.ICDoacao>, BiblioLivri.View.CDoacao.ICDoacao {
        
        public CDoacaoClient() {
        }
        
        public CDoacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDoacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDoacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDoacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] Incluir(BiblioLivri.View.CDoacao.TBDoacao oDoacao) {
            return base.Channel.Incluir(oDoacao);
        }
        
        public System.Threading.Tasks.Task<int[]> IncluirAsync(BiblioLivri.View.CDoacao.TBDoacao oDoacao) {
            return base.Channel.IncluirAsync(oDoacao);
        }
        
        public void Alterar(BiblioLivri.View.CDoacao.TBDoacao oDoacao) {
            base.Channel.Alterar(oDoacao);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CDoacao.TBDoacao oDoacao) {
            return base.Channel.AlterarAsync(oDoacao);
        }
        
        public void Excluir(BiblioLivri.View.CDoacao.TBDoacao oDoacao) {
            base.Channel.Excluir(oDoacao);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CDoacao.TBDoacao oDoacao) {
            return base.Channel.ExcluirAsync(oDoacao);
        }
        
        public BiblioLivri.View.CDoacao.TBDoacao SelecionaPK(int codigo) {
            return base.Channel.SelecionaPK(codigo);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CDoacao.TBDoacao> SelecionaPKAsync(int codigo) {
            return base.Channel.SelecionaPKAsync(codigo);
        }
        
        public BiblioLivri.View.CDoacao.TBDoacao[] SelecionaTodos() {
            return base.Channel.SelecionaTodos();
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CDoacao.TBDoacao[]> SelecionaTodosAsync() {
            return base.Channel.SelecionaTodosAsync();
        }
        
        public BiblioLivri.View.CDoacao.TBDoacao[] SelecionaTodosCriterio(string Criterio, int TipoPesquisa) {
            return base.Channel.SelecionaTodosCriterio(Criterio, TipoPesquisa);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CDoacao.TBDoacao[]> SelecionaTodosCriterioAsync(string Criterio, int TipoPesquisa) {
            return base.Channel.SelecionaTodosCriterioAsync(Criterio, TipoPesquisa);
        }
    }
}
