//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLivri.View.CCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBCliente", Namespace="http://schemas.datacontract.org/2004/07/BiblioLivri.Model")]
    [System.SerializableAttribute()]
    public partial class TBCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliCEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliCPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliEnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CliNumCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliSobrenomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CliTelefoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliCEP {
            get {
                return this.CliCEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CliCEPField, value) != true)) {
                    this.CliCEPField = value;
                    this.RaisePropertyChanged("CliCEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliCPF {
            get {
                return this.CliCPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CliCPFField, value) != true)) {
                    this.CliCPFField = value;
                    this.RaisePropertyChanged("CliCPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliCelular {
            get {
                return this.CliCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CliCelularField, value) != true)) {
                    this.CliCelularField = value;
                    this.RaisePropertyChanged("CliCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliCidade {
            get {
                return this.CliCidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CliCidadeField, value) != true)) {
                    this.CliCidadeField = value;
                    this.RaisePropertyChanged("CliCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliEmail {
            get {
                return this.CliEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CliEmailField, value) != true)) {
                    this.CliEmailField = value;
                    this.RaisePropertyChanged("CliEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliEndereco {
            get {
                return this.CliEnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.CliEnderecoField, value) != true)) {
                    this.CliEnderecoField = value;
                    this.RaisePropertyChanged("CliEndereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliEstado {
            get {
                return this.CliEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CliEstadoField, value) != true)) {
                    this.CliEstadoField = value;
                    this.RaisePropertyChanged("CliEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliNome {
            get {
                return this.CliNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CliNomeField, value) != true)) {
                    this.CliNomeField = value;
                    this.RaisePropertyChanged("CliNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CliNumCartao {
            get {
                return this.CliNumCartaoField;
            }
            set {
                if ((this.CliNumCartaoField.Equals(value) != true)) {
                    this.CliNumCartaoField = value;
                    this.RaisePropertyChanged("CliNumCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliPais {
            get {
                return this.CliPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.CliPaisField, value) != true)) {
                    this.CliPaisField = value;
                    this.RaisePropertyChanged("CliPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliSobrenome {
            get {
                return this.CliSobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CliSobrenomeField, value) != true)) {
                    this.CliSobrenomeField = value;
                    this.RaisePropertyChanged("CliSobrenome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CliTelefone {
            get {
                return this.CliTelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CliTelefoneField, value) != true)) {
                    this.CliTelefoneField = value;
                    this.RaisePropertyChanged("CliTelefone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CCliente.ICCliente")]
    public interface ICCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/Incluir", ReplyAction="http://tempuri.org/ICCliente/IncluirResponse")]
        void Incluir(BiblioLivri.View.CCliente.TBCliente oCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/Incluir", ReplyAction="http://tempuri.org/ICCliente/IncluirResponse")]
        System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CCliente.TBCliente oCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/Alterar", ReplyAction="http://tempuri.org/ICCliente/AlterarResponse")]
        void Alterar(BiblioLivri.View.CCliente.TBCliente oCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/Alterar", ReplyAction="http://tempuri.org/ICCliente/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CCliente.TBCliente oCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/Excluir", ReplyAction="http://tempuri.org/ICCliente/ExcluirResponse")]
        void Excluir(BiblioLivri.View.CCliente.TBCliente oCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/Excluir", ReplyAction="http://tempuri.org/ICCliente/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CCliente.TBCliente oCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/SelecionaPK", ReplyAction="http://tempuri.org/ICCliente/SelecionaPKResponse")]
        BiblioLivri.View.CCliente.TBCliente SelecionaPK(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/SelecionaPK", ReplyAction="http://tempuri.org/ICCliente/SelecionaPKResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CCliente.TBCliente> SelecionaPKAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/SelecionaTodos", ReplyAction="http://tempuri.org/ICCliente/SelecionaTodosResponse")]
        BiblioLivri.View.CCliente.TBCliente[] SelecionaTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/SelecionaTodos", ReplyAction="http://tempuri.org/ICCliente/SelecionaTodosResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CCliente.TBCliente[]> SelecionaTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/SelecionaTodosConsulta", ReplyAction="http://tempuri.org/ICCliente/SelecionaTodosConsultaResponse")]
        BiblioLivri.View.CCliente.TBCliente[] SelecionaTodosConsulta(int Criteria, string Criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/SelecionaTodosConsulta", ReplyAction="http://tempuri.org/ICCliente/SelecionaTodosConsultaResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CCliente.TBCliente[]> SelecionaTodosConsultaAsync(int Criteria, string Criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/ValidaCPF", ReplyAction="http://tempuri.org/ICCliente/ValidaCPFResponse")]
        bool ValidaCPF(string CPF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCliente/ValidaCPF", ReplyAction="http://tempuri.org/ICCliente/ValidaCPFResponse")]
        System.Threading.Tasks.Task<bool> ValidaCPFAsync(string CPF);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICClienteChannel : BiblioLivri.View.CCliente.ICCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CClienteClient : System.ServiceModel.ClientBase<BiblioLivri.View.CCliente.ICCliente>, BiblioLivri.View.CCliente.ICCliente {
        
        public CClienteClient() {
        }
        
        public CClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Incluir(BiblioLivri.View.CCliente.TBCliente oCliente) {
            base.Channel.Incluir(oCliente);
        }
        
        public System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CCliente.TBCliente oCliente) {
            return base.Channel.IncluirAsync(oCliente);
        }
        
        public void Alterar(BiblioLivri.View.CCliente.TBCliente oCliente) {
            base.Channel.Alterar(oCliente);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CCliente.TBCliente oCliente) {
            return base.Channel.AlterarAsync(oCliente);
        }
        
        public void Excluir(BiblioLivri.View.CCliente.TBCliente oCliente) {
            base.Channel.Excluir(oCliente);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CCliente.TBCliente oCliente) {
            return base.Channel.ExcluirAsync(oCliente);
        }
        
        public BiblioLivri.View.CCliente.TBCliente SelecionaPK(int codigo) {
            return base.Channel.SelecionaPK(codigo);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CCliente.TBCliente> SelecionaPKAsync(int codigo) {
            return base.Channel.SelecionaPKAsync(codigo);
        }
        
        public BiblioLivri.View.CCliente.TBCliente[] SelecionaTodos() {
            return base.Channel.SelecionaTodos();
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CCliente.TBCliente[]> SelecionaTodosAsync() {
            return base.Channel.SelecionaTodosAsync();
        }
        
        public BiblioLivri.View.CCliente.TBCliente[] SelecionaTodosConsulta(int Criteria, string Criterio) {
            return base.Channel.SelecionaTodosConsulta(Criteria, Criterio);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CCliente.TBCliente[]> SelecionaTodosConsultaAsync(int Criteria, string Criterio) {
            return base.Channel.SelecionaTodosConsultaAsync(Criteria, Criterio);
        }
        
        public bool ValidaCPF(string CPF) {
            return base.Channel.ValidaCPF(CPF);
        }
        
        public System.Threading.Tasks.Task<bool> ValidaCPFAsync(string CPF) {
            return base.Channel.ValidaCPFAsync(CPF);
        }
    }
}
