//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLivri.View.CItemDoacao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBItemDoacao", Namespace="http://schemas.datacontract.org/2004/07/BiblioLivri.Model")]
    [System.SerializableAttribute()]
    public partial class TBItemDoacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ItemDataDoacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemNumCopiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemNumDoacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ItemDataDoacao {
            get {
                return this.ItemDataDoacaoField;
            }
            set {
                if ((this.ItemDataDoacaoField.Equals(value) != true)) {
                    this.ItemDataDoacaoField = value;
                    this.RaisePropertyChanged("ItemDataDoacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemNumCopia {
            get {
                return this.ItemNumCopiaField;
            }
            set {
                if ((this.ItemNumCopiaField.Equals(value) != true)) {
                    this.ItemNumCopiaField = value;
                    this.RaisePropertyChanged("ItemNumCopia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemNumDoacao {
            get {
                return this.ItemNumDoacaoField;
            }
            set {
                if ((this.ItemNumDoacaoField.Equals(value) != true)) {
                    this.ItemNumDoacaoField = value;
                    this.RaisePropertyChanged("ItemNumDoacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CItemDoacao.ICItemDoacao")]
    public interface ICItemDoacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICItemDoacao/Incluir", ReplyAction="http://tempuri.org/ICItemDoacao/IncluirResponse")]
        void Incluir(BiblioLivri.View.CItemDoacao.TBItemDoacao oDoacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICItemDoacao/Incluir", ReplyAction="http://tempuri.org/ICItemDoacao/IncluirResponse")]
        System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CItemDoacao.TBItemDoacao oDoacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICItemDoacao/IncluirTodos", ReplyAction="http://tempuri.org/ICItemDoacao/IncluirTodosResponse")]
        void IncluirTodos(BiblioLivri.View.CItemDoacao.TBItemDoacao[] oDoacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICItemDoacao/IncluirTodos", ReplyAction="http://tempuri.org/ICItemDoacao/IncluirTodosResponse")]
        System.Threading.Tasks.Task IncluirTodosAsync(BiblioLivri.View.CItemDoacao.TBItemDoacao[] oDoacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICItemDoacao/SelecionaPK", ReplyAction="http://tempuri.org/ICItemDoacao/SelecionaPKResponse")]
        BiblioLivri.View.CItemDoacao.TBItemDoacao SelecionaPK(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICItemDoacao/SelecionaPK", ReplyAction="http://tempuri.org/ICItemDoacao/SelecionaPKResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CItemDoacao.TBItemDoacao> SelecionaPKAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICItemDoacao/SelecionaTodos", ReplyAction="http://tempuri.org/ICItemDoacao/SelecionaTodosResponse")]
        BiblioLivri.View.CItemDoacao.TBItemDoacao[] SelecionaTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICItemDoacao/SelecionaTodos", ReplyAction="http://tempuri.org/ICItemDoacao/SelecionaTodosResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CItemDoacao.TBItemDoacao[]> SelecionaTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICItemDoacao/SelecionaTodosCriterio", ReplyAction="http://tempuri.org/ICItemDoacao/SelecionaTodosCriterioResponse")]
        BiblioLivri.View.CItemDoacao.TBItemDoacao[] SelecionaTodosCriterio(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICItemDoacao/SelecionaTodosCriterio", ReplyAction="http://tempuri.org/ICItemDoacao/SelecionaTodosCriterioResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CItemDoacao.TBItemDoacao[]> SelecionaTodosCriterioAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICItemDoacaoChannel : BiblioLivri.View.CItemDoacao.ICItemDoacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CItemDoacaoClient : System.ServiceModel.ClientBase<BiblioLivri.View.CItemDoacao.ICItemDoacao>, BiblioLivri.View.CItemDoacao.ICItemDoacao {
        
        public CItemDoacaoClient() {
        }
        
        public CItemDoacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CItemDoacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CItemDoacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CItemDoacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Incluir(BiblioLivri.View.CItemDoacao.TBItemDoacao oDoacao) {
            base.Channel.Incluir(oDoacao);
        }
        
        public System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CItemDoacao.TBItemDoacao oDoacao) {
            return base.Channel.IncluirAsync(oDoacao);
        }
        
        public void IncluirTodos(BiblioLivri.View.CItemDoacao.TBItemDoacao[] oDoacao) {
            base.Channel.IncluirTodos(oDoacao);
        }
        
        public System.Threading.Tasks.Task IncluirTodosAsync(BiblioLivri.View.CItemDoacao.TBItemDoacao[] oDoacao) {
            return base.Channel.IncluirTodosAsync(oDoacao);
        }
        
        public BiblioLivri.View.CItemDoacao.TBItemDoacao SelecionaPK(int codigo) {
            return base.Channel.SelecionaPK(codigo);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CItemDoacao.TBItemDoacao> SelecionaPKAsync(int codigo) {
            return base.Channel.SelecionaPKAsync(codigo);
        }
        
        public BiblioLivri.View.CItemDoacao.TBItemDoacao[] SelecionaTodos() {
            return base.Channel.SelecionaTodos();
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CItemDoacao.TBItemDoacao[]> SelecionaTodosAsync() {
            return base.Channel.SelecionaTodosAsync();
        }
        
        public BiblioLivri.View.CItemDoacao.TBItemDoacao[] SelecionaTodosCriterio(int codigo) {
            return base.Channel.SelecionaTodosCriterio(codigo);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CItemDoacao.TBItemDoacao[]> SelecionaTodosCriterioAsync(int codigo) {
            return base.Channel.SelecionaTodosCriterioAsync(codigo);
        }
    }
}
