//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLivri.View.CFuncionario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBFuncionario", Namespace="http://schemas.datacontract.org/2004/07/BiblioLivri.Model")]
    [System.SerializableAttribute()]
    public partial class TBFuncionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunCEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunCPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunPISField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FunSalDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FunSalarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunSobrenomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunTelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_funcionarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunCEP {
            get {
                return this.FunCEPField;
            }
            set {
                if ((object.ReferenceEquals(this.FunCEPField, value) != true)) {
                    this.FunCEPField = value;
                    this.RaisePropertyChanged("FunCEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunCPF {
            get {
                return this.FunCPFField;
            }
            set {
                if ((object.ReferenceEquals(this.FunCPFField, value) != true)) {
                    this.FunCPFField = value;
                    this.RaisePropertyChanged("FunCPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunCelular {
            get {
                return this.FunCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.FunCelularField, value) != true)) {
                    this.FunCelularField = value;
                    this.RaisePropertyChanged("FunCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunCidade {
            get {
                return this.FunCidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.FunCidadeField, value) != true)) {
                    this.FunCidadeField = value;
                    this.RaisePropertyChanged("FunCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunComplemento {
            get {
                return this.FunComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.FunComplementoField, value) != true)) {
                    this.FunComplementoField = value;
                    this.RaisePropertyChanged("FunComplemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunEmail {
            get {
                return this.FunEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.FunEmailField, value) != true)) {
                    this.FunEmailField = value;
                    this.RaisePropertyChanged("FunEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunEstado {
            get {
                return this.FunEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FunEstadoField, value) != true)) {
                    this.FunEstadoField = value;
                    this.RaisePropertyChanged("FunEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunNome {
            get {
                return this.FunNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.FunNomeField, value) != true)) {
                    this.FunNomeField = value;
                    this.RaisePropertyChanged("FunNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunNumero {
            get {
                return this.FunNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.FunNumeroField, value) != true)) {
                    this.FunNumeroField = value;
                    this.RaisePropertyChanged("FunNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunPIS {
            get {
                return this.FunPISField;
            }
            set {
                if ((object.ReferenceEquals(this.FunPISField, value) != true)) {
                    this.FunPISField = value;
                    this.RaisePropertyChanged("FunPIS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunPais {
            get {
                return this.FunPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.FunPaisField, value) != true)) {
                    this.FunPaisField = value;
                    this.RaisePropertyChanged("FunPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FunSalDesconto {
            get {
                return this.FunSalDescontoField;
            }
            set {
                if ((this.FunSalDescontoField.Equals(value) != true)) {
                    this.FunSalDescontoField = value;
                    this.RaisePropertyChanged("FunSalDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FunSalario {
            get {
                return this.FunSalarioField;
            }
            set {
                if ((this.FunSalarioField.Equals(value) != true)) {
                    this.FunSalarioField = value;
                    this.RaisePropertyChanged("FunSalario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunSobrenome {
            get {
                return this.FunSobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.FunSobrenomeField, value) != true)) {
                    this.FunSobrenomeField = value;
                    this.RaisePropertyChanged("FunSobrenome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunTelefone {
            get {
                return this.FunTelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.FunTelefoneField, value) != true)) {
                    this.FunTelefoneField = value;
                    this.RaisePropertyChanged("FunTelefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_funcionario {
            get {
                return this.id_funcionarioField;
            }
            set {
                if ((this.id_funcionarioField.Equals(value) != true)) {
                    this.id_funcionarioField = value;
                    this.RaisePropertyChanged("id_funcionario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CFuncionario.ICFuncionario")]
    public interface ICFuncionario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/Incluir", ReplyAction="http://tempuri.org/ICFuncionario/IncluirResponse")]
        void Incluir(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/Incluir", ReplyAction="http://tempuri.org/ICFuncionario/IncluirResponse")]
        System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/Alterar", ReplyAction="http://tempuri.org/ICFuncionario/AlterarResponse")]
        void Alterar(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/Alterar", ReplyAction="http://tempuri.org/ICFuncionario/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/Excluir", ReplyAction="http://tempuri.org/ICFuncionario/ExcluirResponse")]
        void Excluir(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/Excluir", ReplyAction="http://tempuri.org/ICFuncionario/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/SelecionaPK", ReplyAction="http://tempuri.org/ICFuncionario/SelecionaPKResponse")]
        BiblioLivri.View.CFuncionario.TBFuncionario SelecionaPK(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/SelecionaPK", ReplyAction="http://tempuri.org/ICFuncionario/SelecionaPKResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CFuncionario.TBFuncionario> SelecionaPKAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/SelecionaTodos", ReplyAction="http://tempuri.org/ICFuncionario/SelecionaTodosResponse")]
        BiblioLivri.View.CFuncionario.TBFuncionario[] SelecionaTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/SelecionaTodos", ReplyAction="http://tempuri.org/ICFuncionario/SelecionaTodosResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CFuncionario.TBFuncionario[]> SelecionaTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/ValidaCPF", ReplyAction="http://tempuri.org/ICFuncionario/ValidaCPFResponse")]
        bool ValidaCPF(string CPF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFuncionario/ValidaCPF", ReplyAction="http://tempuri.org/ICFuncionario/ValidaCPFResponse")]
        System.Threading.Tasks.Task<bool> ValidaCPFAsync(string CPF);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICFuncionarioChannel : BiblioLivri.View.CFuncionario.ICFuncionario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CFuncionarioClient : System.ServiceModel.ClientBase<BiblioLivri.View.CFuncionario.ICFuncionario>, BiblioLivri.View.CFuncionario.ICFuncionario {
        
        public CFuncionarioClient() {
        }
        
        public CFuncionarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CFuncionarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFuncionarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFuncionarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Incluir(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario) {
            base.Channel.Incluir(oFuncionario);
        }
        
        public System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario) {
            return base.Channel.IncluirAsync(oFuncionario);
        }
        
        public void Alterar(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario) {
            base.Channel.Alterar(oFuncionario);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario) {
            return base.Channel.AlterarAsync(oFuncionario);
        }
        
        public void Excluir(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario) {
            base.Channel.Excluir(oFuncionario);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CFuncionario.TBFuncionario oFuncionario) {
            return base.Channel.ExcluirAsync(oFuncionario);
        }
        
        public BiblioLivri.View.CFuncionario.TBFuncionario SelecionaPK(int codigo) {
            return base.Channel.SelecionaPK(codigo);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CFuncionario.TBFuncionario> SelecionaPKAsync(int codigo) {
            return base.Channel.SelecionaPKAsync(codigo);
        }
        
        public BiblioLivri.View.CFuncionario.TBFuncionario[] SelecionaTodos() {
            return base.Channel.SelecionaTodos();
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CFuncionario.TBFuncionario[]> SelecionaTodosAsync() {
            return base.Channel.SelecionaTodosAsync();
        }
        
        public bool ValidaCPF(string CPF) {
            return base.Channel.ValidaCPF(CPF);
        }
        
        public System.Threading.Tasks.Task<bool> ValidaCPFAsync(string CPF) {
            return base.Channel.ValidaCPFAsync(CPF);
        }
    }
}
