//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLivri.View.CFilme {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBFilme", Namespace="http://schemas.datacontract.org/2004/07/BiblioLivri.Model")]
    [System.SerializableAttribute()]
    public partial class TBFilme : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilAnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FilCapaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilDuracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilIdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilTituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_DiretorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_FilmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_MidiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilAno {
            get {
                return this.FilAnoField;
            }
            set {
                if ((object.ReferenceEquals(this.FilAnoField, value) != true)) {
                    this.FilAnoField = value;
                    this.RaisePropertyChanged("FilAno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FilCapa {
            get {
                return this.FilCapaField;
            }
            set {
                if ((object.ReferenceEquals(this.FilCapaField, value) != true)) {
                    this.FilCapaField = value;
                    this.RaisePropertyChanged("FilCapa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilDescricao {
            get {
                return this.FilDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FilDescricaoField, value) != true)) {
                    this.FilDescricaoField = value;
                    this.RaisePropertyChanged("FilDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilDuracao {
            get {
                return this.FilDuracaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FilDuracaoField, value) != true)) {
                    this.FilDuracaoField = value;
                    this.RaisePropertyChanged("FilDuracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilIdioma {
            get {
                return this.FilIdiomaField;
            }
            set {
                if ((object.ReferenceEquals(this.FilIdiomaField, value) != true)) {
                    this.FilIdiomaField = value;
                    this.RaisePropertyChanged("FilIdioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilPais {
            get {
                return this.FilPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.FilPaisField, value) != true)) {
                    this.FilPaisField = value;
                    this.RaisePropertyChanged("FilPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilTitulo {
            get {
                return this.FilTituloField;
            }
            set {
                if ((object.ReferenceEquals(this.FilTituloField, value) != true)) {
                    this.FilTituloField = value;
                    this.RaisePropertyChanged("FilTitulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Diretor {
            get {
                return this.id_DiretorField;
            }
            set {
                if ((this.id_DiretorField.Equals(value) != true)) {
                    this.id_DiretorField = value;
                    this.RaisePropertyChanged("id_Diretor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Filme {
            get {
                return this.id_FilmeField;
            }
            set {
                if ((this.id_FilmeField.Equals(value) != true)) {
                    this.id_FilmeField = value;
                    this.RaisePropertyChanged("id_Filme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Genero {
            get {
                return this.id_GeneroField;
            }
            set {
                if ((this.id_GeneroField.Equals(value) != true)) {
                    this.id_GeneroField = value;
                    this.RaisePropertyChanged("id_Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Midia {
            get {
                return this.id_MidiaField;
            }
            set {
                if ((this.id_MidiaField.Equals(value) != true)) {
                    this.id_MidiaField = value;
                    this.RaisePropertyChanged("id_Midia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CFilme.ICFilme")]
    public interface ICFilme {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFilme/Incluir", ReplyAction="http://tempuri.org/ICFilme/IncluirResponse")]
        void Incluir(BiblioLivri.View.CFilme.TBFilme oFilme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFilme/Incluir", ReplyAction="http://tempuri.org/ICFilme/IncluirResponse")]
        System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CFilme.TBFilme oFilme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFilme/Alterar", ReplyAction="http://tempuri.org/ICFilme/AlterarResponse")]
        void Alterar(BiblioLivri.View.CFilme.TBFilme oFilme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFilme/Alterar", ReplyAction="http://tempuri.org/ICFilme/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CFilme.TBFilme oFilme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFilme/Excluir", ReplyAction="http://tempuri.org/ICFilme/ExcluirResponse")]
        void Excluir(BiblioLivri.View.CFilme.TBFilme oFilme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFilme/Excluir", ReplyAction="http://tempuri.org/ICFilme/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CFilme.TBFilme oFilme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFilme/SelecionaPK", ReplyAction="http://tempuri.org/ICFilme/SelecionaPKResponse")]
        BiblioLivri.View.CFilme.TBFilme SelecionaPK(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFilme/SelecionaPK", ReplyAction="http://tempuri.org/ICFilme/SelecionaPKResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CFilme.TBFilme> SelecionaPKAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFilme/SelecionaTodos", ReplyAction="http://tempuri.org/ICFilme/SelecionaTodosResponse")]
        BiblioLivri.View.CFilme.TBFilme[] SelecionaTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFilme/SelecionaTodos", ReplyAction="http://tempuri.org/ICFilme/SelecionaTodosResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CFilme.TBFilme[]> SelecionaTodosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICFilmeChannel : BiblioLivri.View.CFilme.ICFilme, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CFilmeClient : System.ServiceModel.ClientBase<BiblioLivri.View.CFilme.ICFilme>, BiblioLivri.View.CFilme.ICFilme {
        
        public CFilmeClient() {
        }
        
        public CFilmeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CFilmeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFilmeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFilmeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Incluir(BiblioLivri.View.CFilme.TBFilme oFilme) {
            base.Channel.Incluir(oFilme);
        }
        
        public System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CFilme.TBFilme oFilme) {
            return base.Channel.IncluirAsync(oFilme);
        }
        
        public void Alterar(BiblioLivri.View.CFilme.TBFilme oFilme) {
            base.Channel.Alterar(oFilme);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CFilme.TBFilme oFilme) {
            return base.Channel.AlterarAsync(oFilme);
        }
        
        public void Excluir(BiblioLivri.View.CFilme.TBFilme oFilme) {
            base.Channel.Excluir(oFilme);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CFilme.TBFilme oFilme) {
            return base.Channel.ExcluirAsync(oFilme);
        }
        
        public BiblioLivri.View.CFilme.TBFilme SelecionaPK(int codigo) {
            return base.Channel.SelecionaPK(codigo);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CFilme.TBFilme> SelecionaPKAsync(int codigo) {
            return base.Channel.SelecionaPKAsync(codigo);
        }
        
        public BiblioLivri.View.CFilme.TBFilme[] SelecionaTodos() {
            return base.Channel.SelecionaTodos();
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CFilme.TBFilme[]> SelecionaTodosAsync() {
            return base.Channel.SelecionaTodosAsync();
        }
    }
}
