//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLivri.View.CLivro {
    using System.Runtime.Serialization;
    using System;
    using System.Data.Linq;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBLivro", Namespace="http://schemas.datacontract.org/2004/07/BiblioLivri.Model")]
    [System.SerializableAttribute()]
    public partial class TBLivro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiAnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiCDUField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        //private BiblioLivri.View.CLivro.Binary LiCapaField;
        private byte[] LiCapaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiIdiomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiNumPaginasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiTituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> id_CoAutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_EditoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_LivroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiAno {
            get {
                return this.LiAnoField;
            }
            set {
                if ((object.ReferenceEquals(this.LiAnoField, value) != true)) {
                    this.LiAnoField = value;
                    this.RaisePropertyChanged("LiAno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiCDU {
            get {
                return this.LiCDUField;
            }
            set {
                if ((object.ReferenceEquals(this.LiCDUField, value) != true)) {
                    this.LiCDUField = value;
                    this.RaisePropertyChanged("LiCDU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        // public BiblioLivri.View.CLivro.Binary LiCapa {
        public byte[] LiCapa
        {
            get {
                return this.LiCapaField;
            }
            set {
                if ((object.ReferenceEquals(this.LiCapaField, value) != true)) {
                    this.LiCapaField = value;
                    this.RaisePropertyChanged("LiCapa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiISBN {
            get {
                return this.LiISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.LiISBNField, value) != true)) {
                    this.LiISBNField = value;
                    this.RaisePropertyChanged("LiISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiIdioma {
            get {
                return this.LiIdiomaField;
            }
            set {
                if ((object.ReferenceEquals(this.LiIdiomaField, value) != true)) {
                    this.LiIdiomaField = value;
                    this.RaisePropertyChanged("LiIdioma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiNumPaginas {
            get {
                return this.LiNumPaginasField;
            }
            set {
                if ((object.ReferenceEquals(this.LiNumPaginasField, value) != true)) {
                    this.LiNumPaginasField = value;
                    this.RaisePropertyChanged("LiNumPaginas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiPais {
            get {
                return this.LiPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.LiPaisField, value) != true)) {
                    this.LiPaisField = value;
                    this.RaisePropertyChanged("LiPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiTitulo {
            get {
                return this.LiTituloField;
            }
            set {
                if ((object.ReferenceEquals(this.LiTituloField, value) != true)) {
                    this.LiTituloField = value;
                    this.RaisePropertyChanged("LiTitulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Autor {
            get {
                return this.id_AutorField;
            }
            set {
                if ((this.id_AutorField.Equals(value) != true)) {
                    this.id_AutorField = value;
                    this.RaisePropertyChanged("id_Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_CoAutor {
            get {
                return this.id_CoAutorField;
            }
            set {
                if ((this.id_CoAutorField.Equals(value) != true)) {
                    this.id_CoAutorField = value;
                    this.RaisePropertyChanged("id_CoAutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Editora {
            get {
                return this.id_EditoraField;
            }
            set {
                if ((this.id_EditoraField.Equals(value) != true)) {
                    this.id_EditoraField = value;
                    this.RaisePropertyChanged("id_Editora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Genero {
            get {
                return this.id_GeneroField;
            }
            set {
                if ((this.id_GeneroField.Equals(value) != true)) {
                    this.id_GeneroField = value;
                    this.RaisePropertyChanged("id_Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Livro {
            get {
                return this.id_LivroField;
            }
            set {
                if ((this.id_LivroField.Equals(value) != true)) {
                    this.id_LivroField = value;
                    this.RaisePropertyChanged("id_Livro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    [System.SerializableAttribute()]
    public partial class Binary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
       // private System.Data.Linq.Binary v;
       // private byte[] imgbytesize;

        /*public Binary(byte[] imgbytesize)
        {
            this.imgbytesize = imgbytesize;
        }*/


        /*public Binary(System.Data.Linq.Binary v)
        {
            this.v = v;
        }*/

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

       /* public static implicit operator Binary(System.Data.Linq.Binary v)
        {
            CLivro.Binary a = new Binary(v);
            return a;
        }*/
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CLivro.ICLivro")]
    public interface ICLivro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Incluir", ReplyAction="http://tempuri.org/ICLivro/IncluirResponse")]
        void Incluir(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Incluir", ReplyAction="http://tempuri.org/ICLivro/IncluirResponse")]
        System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Alterar", ReplyAction="http://tempuri.org/ICLivro/AlterarResponse")]
        void Alterar(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Alterar", ReplyAction="http://tempuri.org/ICLivro/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Excluir", ReplyAction="http://tempuri.org/ICLivro/ExcluirResponse")]
        void Excluir(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Excluir", ReplyAction="http://tempuri.org/ICLivro/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/SelecionaPK", ReplyAction="http://tempuri.org/ICLivro/SelecionaPKResponse")]
        BiblioLivri.View.CLivro.TBLivro SelecionaPK(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/SelecionaPK", ReplyAction="http://tempuri.org/ICLivro/SelecionaPKResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CLivro.TBLivro> SelecionaPKAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/SelecionaTodos", ReplyAction="http://tempuri.org/ICLivro/SelecionaTodosResponse")]
        BiblioLivri.View.CLivro.TBLivro[] SelecionaTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/SelecionaTodos", ReplyAction="http://tempuri.org/ICLivro/SelecionaTodosResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CLivro.TBLivro[]> SelecionaTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/ValidaISBN", ReplyAction="http://tempuri.org/ICLivro/ValidaISBNResponse")]
        bool ValidaISBN(string ISBN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/ValidaISBN", ReplyAction="http://tempuri.org/ICLivro/ValidaISBNResponse")]
        System.Threading.Tasks.Task<bool> ValidaISBNAsync(string ISBN);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICLivroChannel : BiblioLivri.View.CLivro.ICLivro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CLivroClient : System.ServiceModel.ClientBase<BiblioLivri.View.CLivro.ICLivro>, BiblioLivri.View.CLivro.ICLivro {
        
        public CLivroClient() {
        }
        
        public CLivroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CLivroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CLivroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CLivroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Incluir(BiblioLivri.View.CLivro.TBLivro oLivro) {
            base.Channel.Incluir(oLivro);
        }
        
        public System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CLivro.TBLivro oLivro) {
            return base.Channel.IncluirAsync(oLivro);
        }
        
        public void Alterar(BiblioLivri.View.CLivro.TBLivro oLivro) {
            base.Channel.Alterar(oLivro);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CLivro.TBLivro oLivro) {
            return base.Channel.AlterarAsync(oLivro);
        }
        
        public void Excluir(BiblioLivri.View.CLivro.TBLivro oLivro) {
            base.Channel.Excluir(oLivro);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CLivro.TBLivro oLivro) {
            return base.Channel.ExcluirAsync(oLivro);
        }
        
        public BiblioLivri.View.CLivro.TBLivro SelecionaPK(int codigo) {
            return base.Channel.SelecionaPK(codigo);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CLivro.TBLivro> SelecionaPKAsync(int codigo) {
            return base.Channel.SelecionaPKAsync(codigo);
        }
        
        public BiblioLivri.View.CLivro.TBLivro[] SelecionaTodos() {
            return base.Channel.SelecionaTodos();
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CLivro.TBLivro[]> SelecionaTodosAsync() {
            return base.Channel.SelecionaTodosAsync();
        }
        
        public bool ValidaISBN(string ISBN) {
            return base.Channel.ValidaISBN(ISBN);
        }
        
        public System.Threading.Tasks.Task<bool> ValidaISBNAsync(string ISBN) {
            return base.Channel.ValidaISBNAsync(ISBN);
        }
    }
}
