//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioLivri.View.CLivro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBLivro", Namespace="http://schemas.datacontract.org/2004/07/BiblioLivri.Model")]
    [System.SerializableAttribute()]
    public partial class TBLivro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_EditoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiCDUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] LiCapaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiPaginaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LiTituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_autorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_generoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Editora {
            get {
                return this.ID_EditoraField;
            }
            set {
                if ((this.ID_EditoraField.Equals(value) != true)) {
                    this.ID_EditoraField = value;
                    this.RaisePropertyChanged("ID_Editora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiCDU {
            get {
                return this.LiCDUField;
            }
            set {
                if ((object.ReferenceEquals(this.LiCDUField, value) != true)) {
                    this.LiCDUField = value;
                    this.RaisePropertyChanged("LiCDU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] LiCapa {
            get {
                return this.LiCapaField;
            }
            set {
                if ((object.ReferenceEquals(this.LiCapaField, value) != true)) {
                    this.LiCapaField = value;
                    this.RaisePropertyChanged("LiCapa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiISBN {
            get {
                return this.LiISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.LiISBNField, value) != true)) {
                    this.LiISBNField = value;
                    this.RaisePropertyChanged("LiISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiPagina {
            get {
                return this.LiPaginaField;
            }
            set {
                if ((object.ReferenceEquals(this.LiPaginaField, value) != true)) {
                    this.LiPaginaField = value;
                    this.RaisePropertyChanged("LiPagina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiPais {
            get {
                return this.LiPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.LiPaisField, value) != true)) {
                    this.LiPaisField = value;
                    this.RaisePropertyChanged("LiPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LiTitulo {
            get {
                return this.LiTituloField;
            }
            set {
                if ((object.ReferenceEquals(this.LiTituloField, value) != true)) {
                    this.LiTituloField = value;
                    this.RaisePropertyChanged("LiTitulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_autor {
            get {
                return this.id_autorField;
            }
            set {
                if ((this.id_autorField.Equals(value) != true)) {
                    this.id_autorField = value;
                    this.RaisePropertyChanged("id_autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_genero {
            get {
                return this.id_generoField;
            }
            set {
                if ((this.id_generoField.Equals(value) != true)) {
                    this.id_generoField = value;
                    this.RaisePropertyChanged("id_genero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CLivro.ICLivro")]
    public interface ICLivro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Incluir", ReplyAction="http://tempuri.org/ICLivro/IncluirResponse")]
        void Incluir(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Incluir", ReplyAction="http://tempuri.org/ICLivro/IncluirResponse")]
        System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Alterar", ReplyAction="http://tempuri.org/ICLivro/AlterarResponse")]
        void Alterar(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Alterar", ReplyAction="http://tempuri.org/ICLivro/AlterarResponse")]
        System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Excluir", ReplyAction="http://tempuri.org/ICLivro/ExcluirResponse")]
        void Excluir(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/Excluir", ReplyAction="http://tempuri.org/ICLivro/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CLivro.TBLivro oLivro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/SelecionaPK", ReplyAction="http://tempuri.org/ICLivro/SelecionaPKResponse")]
        BiblioLivri.View.CLivro.TBLivro SelecionaPK(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/SelecionaPK", ReplyAction="http://tempuri.org/ICLivro/SelecionaPKResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CLivro.TBLivro> SelecionaPKAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/SelecionaTodos", ReplyAction="http://tempuri.org/ICLivro/SelecionaTodosResponse")]
        BiblioLivri.View.CLivro.TBLivro[] SelecionaTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/SelecionaTodos", ReplyAction="http://tempuri.org/ICLivro/SelecionaTodosResponse")]
        System.Threading.Tasks.Task<BiblioLivri.View.CLivro.TBLivro[]> SelecionaTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/ValidaISBN", ReplyAction="http://tempuri.org/ICLivro/ValidaISBNResponse")]
        bool ValidaISBN(string ISBN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICLivro/ValidaISBN", ReplyAction="http://tempuri.org/ICLivro/ValidaISBNResponse")]
        System.Threading.Tasks.Task<bool> ValidaISBNAsync(string ISBN);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICLivroChannel : BiblioLivri.View.CLivro.ICLivro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CLivroClient : System.ServiceModel.ClientBase<BiblioLivri.View.CLivro.ICLivro>, BiblioLivri.View.CLivro.ICLivro {
        
        public CLivroClient() {
        }
        
        public CLivroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CLivroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CLivroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CLivroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Incluir(BiblioLivri.View.CLivro.TBLivro oLivro) {
            base.Channel.Incluir(oLivro);
        }
        
        public System.Threading.Tasks.Task IncluirAsync(BiblioLivri.View.CLivro.TBLivro oLivro) {
            return base.Channel.IncluirAsync(oLivro);
        }
        
        public void Alterar(BiblioLivri.View.CLivro.TBLivro oLivro) {
            base.Channel.Alterar(oLivro);
        }
        
        public System.Threading.Tasks.Task AlterarAsync(BiblioLivri.View.CLivro.TBLivro oLivro) {
            return base.Channel.AlterarAsync(oLivro);
        }
        
        public void Excluir(BiblioLivri.View.CLivro.TBLivro oLivro) {
            base.Channel.Excluir(oLivro);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(BiblioLivri.View.CLivro.TBLivro oLivro) {
            return base.Channel.ExcluirAsync(oLivro);
        }
        
        public BiblioLivri.View.CLivro.TBLivro SelecionaPK(string codigo) {
            return base.Channel.SelecionaPK(codigo);
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CLivro.TBLivro> SelecionaPKAsync(string codigo) {
            return base.Channel.SelecionaPKAsync(codigo);
        }
        
        public BiblioLivri.View.CLivro.TBLivro[] SelecionaTodos() {
            return base.Channel.SelecionaTodos();
        }
        
        public System.Threading.Tasks.Task<BiblioLivri.View.CLivro.TBLivro[]> SelecionaTodosAsync() {
            return base.Channel.SelecionaTodosAsync();
        }
        
        public bool ValidaISBN(string ISBN) {
            return base.Channel.ValidaISBN(ISBN);
        }
        
        public System.Threading.Tasks.Task<bool> ValidaISBNAsync(string ISBN) {
            return base.Channel.ValidaISBNAsync(ISBN);
        }
    }
}
